//request.rest

//POSTS
###

GET http://localhost:3000/post

###
GET http://localhost:3000/post/696b962900d9f5276526f49c

###
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "New Post Title",
  "content": "This is the content of the new post.",
  "sender": 333333333
}

###
GET http://localhost:3000/post?sender=333333333

###
PUT http://localhost:3000/post/696b965500d9f5276526f4a4
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "This is the updated content of the post.",
  "sender": 333
}

###
GET http://localhost:3000/post/696b965500d9f5276526f4a4/comments

###
DELETE http://localhost:3000/post/696b962900d9f5276526f49c

//COMMENTS 

###
GET http://localhost:3000/comments

###
GET http://localhost:3000/comments?postId=69500388b6ed5272b29c4732

###
GET http://localhost:3000/comments/695004b9b6ed5272b29c4748

###
POST http://localhost:3000/comments
Content-Type: application/json

{
  "postId": "69500387b6ed5272b29c4730",
  "content": "This is a comment 1 on the post.",
  "sender": 222
}

###
DELETE http://localhost:3000/comments/696b967600d9f5276526f4ad

###
PUT http://localhost:3000/comments/695004e8b6ed5272b29c474f
Content-Type: application/json

{
  "content": "This is the updated comment content."
}

//USERS

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/69738857cc157ada9919ab38

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "newuser4",
  "email": "newuser4@example.com",
  "password": "newuser4password"
}

###
GET http://localhost:3000/users?username=newuser

###
GET http://localhost:3000/users?email=newuser2@example.com

###
PUT http://localhost:3000/users/64f2c8f4c9ea4b6f8b5d6e1a
Content-Type: application/json

{
  "username": "updateduser",
  "email": "updateduser@example.com",
  "password": "updateduserpassword"
} 

###
DELETE http://localhost:3000/users/697388cccc157ada9919ab48